# Generated by Django 4.1.5 on 2023-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='e9a76473-9b61-4015-ab98-510edaa5c39e', max_length=200),
        ),
    ]
