# Generated by Django 4.1.5 on 2023-03-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_status',
            field=models.CharField(choices=[('on', 'online'), ('off', 'offline'), ('lsr', 'last seen recently')], default='off', max_length=20),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.IntegerField(default=200)),
                ('meeting_time', models.IntegerField(default=15)),
                ('wallet', models.IntegerField(default=2000)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='app.profile')),
            ],
        ),
    ]
