# Generated by Django 4.1.5 on 2023-03-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_activity_status_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
